# Generated by Django 5.1 on 2024-09-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparktechapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=10),
        ),
    ]
